### ISSUE TITLE
Unable to run podenv shell from the example

### ISSUE THREAD

**Issue by morucci** [podenv/podenv#1]
Fom the example in the README.md I use:

```
environments:
  base:
    image: registry.fedoraproject.org/fedora:30
    capabilities:
      autoUpdate: True
      seccomp: True
      selinux: True
    environ:
      LC_ALL: en_US.UTF-8
      SHLVL: 3
      TERM: xterm
    imageCustomizations:
      - sed -e 's/nodocs//' -i /etc/dnf/dnf.conf

  shell:
    capabilities:
      terminal: True
    overlays:
      - bash
    command:
      - /bin/bash
```

But podenv shell command fails with:

```
~/.local/bin/podenv shell        
Overlays without home mount isn't supported 
```

I've changed the shell def to:

```
  shell:
    capabilities:
      terminal: True
    overlays:
      - bash
    home: ~/.config/podenv-home
    command:
      - /bin/bash
```

That seems better but:

```
➜  ~ ~/.local/bin/podenv shell       
SELinux is disabled because /home/fabien/.config/podenv-home doesn't have the container_file_t label.
rsync: mkdir "/home/fabien/~/.config/podenv-home" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(664) [Receiver=3.1.3]
Failed to run rsync --copy-links -a /home/fabien/.config/podenv/overlay/bash/ ~/.config/podenv-home
➜  ~ ls /home/fabien/.config/podenv/overlay/bash/
➜  ~ ls ~/.config/podenv-home
➜  ~ rsync --copy-links -av /home/fabien/.config/podenv/overlay/bash/ ~/.config/podenv-home
sending incremental file list
./
.bashrc

sent 318 bytes  received 38 bytes  712.00 bytes/sec
total size is 187  speedup is 0.53
➜  ~ ls -al ~/.config/podenv-home
total 12
drwxr-xr-x.  2 fabien fabien 4096  6 août  18:08 .
drwxr-xr-x. 56 fabien fabien 4096  7 août  10:55 ..
-rw-r--r--.  1 fabien fabien  187  6 août  18:05 .bashrc
```

Any idea ?
