### ISSUE TITLE
Unable to run a X app issue: "mumble: cannot connect to X server :0"

### ISSUE THREAD

**Issue by morucci** [podenv/podenv#4]
Hi,

I'm trying to run:

```
  mumble:
    packages:
      - mumble
    capabilities:
      x11: True
      pulseaudio: True
      network: True
      ipc: True
    home: ~/.config/podenv-mumble
    command:
      - mumble
      - mumble://softwarefactory-project.io/?version=1.2.0
```

But

```
➜  ~ ~fabien/.local/bin/podenv mumble
SELinux is disabled because capability 'x11' need extra type enforcement that are not currently supported.
UIDMap is required because 'x11' need DAC access to the host file
SELinux is disabled because /tmp/.X11-unix doesn't have the container_file_t label.
SELinux is disabled because /etc/machine-id doesn't have the container_file_t label.
SELinux is disabled because /run/user/1001/pulse doesn't have the container_file_t label.
No protocol specified
mumble: cannot connect to X server :0
```

Should I set "container_file_t" on /tmp/.X11-unix ? or also other /etc/machine-id and /run/user/1001/pulse ?
